import React from 'react';
import { Download, Copy, Check, FileText, Share2, Printer } from 'lucide-react';
import { toast } from 'sonner';
import { jsPDF } from 'jspdf';

interface ReportDisplayProps {
  report: {
    id: string;
    title: string;
    content: string;
    key_findings: string[];
    period: string;
    generated_at: string;
    institution_id?: string;
  };
}

export const ReportDisplay: React.FC<ReportDisplayProps> = ({ report }) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(report.content);
    setCopied(true);
    toast.success('Report copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    // Header
    doc.setFontSize(22);
    doc.setTextColor(99, 102, 241); // Indigo
    doc.text('UCARiq', margin, y);
    
    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Slate-500
    doc.text(`Generated on: ${new Date(report.generated_at).toLocaleDateString()}`, margin, y);
    
    y += 15;
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y, 190, y);
    
    y += 15;
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42); // Slate-900
    doc.text(report.title, margin, y);
    
    y += 10;
    doc.setFontSize(12);
    doc.text(`Period: ${report.period}`, margin, y);
    
    y += 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Findings:', margin, y);
    
    y += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    report.key_findings.forEach(finding => {
      const splitText = doc.splitTextToSize(`• ${finding}`, 170);
      doc.text(splitText, margin + 5, y);
      y += (splitText.length * 6);
    });
    
    y += 10;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Executive Brief:', margin, y);
    
    y += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    // Remove markdown symbols for PDF
    const cleanContent = report.content.replace(/[#*`]/g, '');
    const contentLines = doc.splitTextToSize(cleanContent, 170);
    
    contentLines.forEach((line: string) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += 6;
    });

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Generated by UCARiq · HACK4UCAR 2025 · Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    }

    doc.save(`${report.title.replace(/\s+/g, '_')}.pdf`);
    toast.success('PDF downloaded successfully');
  };

  return (
    <div id="report-display" className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl animate-in fade-in slide-in-from-bottom-8 duration-700">
      <div className="p-8 border-b border-slate-800 bg-slate-950/30 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-xs font-bold text-indigo-400 uppercase tracking-[0.2em]">
            <FileText size={14} />
            Executive Report
          </div>
          <h1 className="text-2xl font-bold text-white leading-tight">{report.title}</h1>
          <div className="flex items-center gap-4 text-sm text-slate-500 mt-2">
            <span>Period: <span className="text-slate-300 font-medium">{report.period}</span></span>
            <div className="w-1 h-1 rounded-full bg-slate-700" />
            <span>Generated: <span className="text-slate-300 font-medium">{new Date(report.generated_at).toLocaleString()}</span></span>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button 
            onClick={handleCopy}
            className="flex items-center gap-2 bg-slate-800 hover:bg-slate-700 text-slate-200 px-4 py-2.5 rounded-xl text-sm font-medium transition-all"
          >
            {copied ? <Check size={16} className="text-green-500" /> : <Copy size={16} />}
            {copied ? 'Copied' : 'Copy'}
          </button>
          <button 
            onClick={handleDownloadPdf}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2.5 rounded-xl text-sm font-bold shadow-lg shadow-indigo-500/10 transition-all active:scale-95"
          >
            <Download size={16} />
            Download PDF
          </button>
        </div>
      </div>

      <div className="p-8 space-y-10">
        {/* Key Findings */}
        <section>
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-6">Key Findings</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {report.key_findings.map((finding, i) => (
              <div key={i} className="bg-slate-950 border border-slate-800 p-5 rounded-2xl relative overflow-hidden group hover:border-indigo-500/50 transition-all">
                <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500 opacity-50" />
                <div className="text-indigo-400 font-bold text-xs mb-2">FINDING #{i+1}</div>
                <p className="text-sm text-slate-300 leading-relaxed font-medium">{finding}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Content */}
        <section className="text-slate-300 leading-relaxed whitespace-pre-wrap font-sans">
          {report.content.split('\n').map((line, i) => {
            if (line.startsWith('##')) {
              return <h2 key={i} className="text-lg font-bold text-white uppercase tracking-wider border-b border-slate-800 pb-2 mt-10 mb-4 first:mt-0">{line.replace('##', '').trim()}</h2>;
            }
            if (line.trim().startsWith('-')) {
               return <li key={i} className="ml-4 mb-2">{line.replace('-', '').trim()}</li>;
            }
            return <p key={i} className="mb-4">{line}</p>;
          })}
        </section>

        <div className="pt-10 border-t border-slate-800 flex justify-between items-center text-[10px] text-slate-500 uppercase font-bold tracking-widest">
          <div className="flex items-center gap-4">
             <div className="flex items-center gap-1">
               <Printer size={12} />
               INTERNAL USE ONLY
             </div>
             <div className="flex items-center gap-1">
               <Share2 size={12} />
               STRICTLY CONFIDENTIAL
             </div>
          </div>
          <div>
            UCARiq AI Intelligence · v1.4
          </div>
        </div>
      </div>
    </div>
  );
};
